{% set name = "spox" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spox-{{ version }}.tar.gz
  sha256: ea99396c2e1afc28f5a21d870df0ad238540f6781bc211435699fd5952c9659b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.0
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8.0
    - numpy
    - onnx >=1.13

test:
  imports:
    - spox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/spox
  summary: A framework for constructing ONNX computational graphs.
  dev_url: https://github.com/quantco/spox
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cbourjau
    - janjagusch
