{% set name = "spox" %}
{% set version = "0.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spox-{{ version }}.tar.gz
  sha256: 8ca8eba0acff9dd6b0227218e477f2c3afc08e2202ea2c0558ec5d21c231b81e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.0
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8.0
    - numpy
    - onnx >=1.13
    - packaging

test:
  imports:
    - spox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/spox
  summary: A framework for constructing ONNX computational graphs.
  dev_url: https://github.com/quantco/spox
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cbourjau
    - janjagusch
