{% set name = "spox" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spox-{{ version }}.tar.gz
  sha256: c436b510a6c0421da0961c01cc6bbb37e1d3b15a61a2a55154c33b647df1f7ee

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8.0
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8.0
    - numpy
    - onnx >=1.13
    - typing_extensions

test:
  imports:
    - spox
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/quantco/spox
  summary: A framework for constructing ONNX computational graphs.
  dev_url: https://github.com/quantco/spox
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cbourjau
    - janjagusch
