context:
  name: "spox"
  version: "0.18.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/spox-${{ version }}.tar.gz
  sha256: f87c05cbf4d0d4b50464d5a1dd4fa34ec00f83bc11b0c06eac4e6fb1a4f3e5ad

build:
  noarch: "python"
  script: pip install . -v
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - onnx >=1.13
    - packaging

tests:
  - python:
      python_version: ${{ python_min }}.*
      imports:
        - spox

about:
  homepage: https://github.com/quantco/spox
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Pythonic framework for building ONNX graphs
  documentation: https://spox.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - cbourjau
    - janjagusch
