context:
  name: "spox"
  version: "0.14.1"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.io/packages/source/${{ name[0] }}/${{ name }}/spox-${{ version }}.tar.gz
  sha256: b2a12dd9449bd6d8ddd9b5b0c1359589c86165dc76bce11d3ef0082972f93b65

build:
  noarch: "python"
  script: pip install . -v
  number: 0

requirements:
  host:
    - python >=3.8.0
    - setuptools
    - setuptools-scm
    - wheel
    - pip
  run:
    - python >=3.8.0
    - numpy
    - onnx >=1.13
    - packaging

tests:
  - python:
      imports:
        - spox

about:
  homepage: https://github.com/quantco/spox
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Jupyter Interactive Widgets
  documentation: https://ipywidgets.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - cbourjau
    - janjagusch
